### ISSUE TITLE
Compressed FGB files are recommended or not?

### ISSUE THREAD

**Issue by kkdd** [flatgeobuf/flatgeobuf#121]
Hello,
Compressed FGB files seem to have the advantage of smaller file size as shown in the ```gzipping``` example below.

Is it recommended, however, with regard to reading speed performance or not? I think that ```*.fgb.gz``` may be read by using [Feature: Compression Streams](https://chromestatus.com/feature/5855937971617792) (Chrome Platform Status), for example.

```
$ wget https://raw.githubusercontent.com/flatgeobuf/flatgeobuf/master/test/data/UScounties.fgb
$ gzip -k UScounties.fgb
$ ls -lh
-rw-r--r-- 1 kkdd  staff    13M  5  6 13:22 UScounties.fgb
-rw-r--r-- 1 kkdd  staff   7.6M  5  6 13:22 UScounties.fgb.gz
```

**Comment by bjornharrtell** [comment]
@kkdd well the answer is - it depends. If you have unlimited bandwidth compression is never useful right?

More serious answer:

It would probably make sense to compress when you transfer over anything else than local disk / RAM. However, compression have another problem and that is that it usually does not support random access, so it is only useful if you want to read the whole thing. There are ways to use compression also for semi-random access but not something readily available. https://github.com/lz4/lz4 is very interesting both because it is very fast and I think it can support semi random access but it needs to be implemented in places like GDAL for which I've made an issue a long time ago (https://github.com/OSGeo/gdal/issues/2201) but it needs a serious time investment. But if you don't want to bother with what might be in the future, gzip is absolutely fine for full payload compression.

**Comment by kkdd** [comment]
Thank you for your explanation.
