### ISSUE TITLE
Serialized geojson is way bigger in size

### ISSUE THREAD

**Issue by bacloud22** [flatgeobuf/flatgeobuf#221]
I'm serializing such [file](https://france-geojson.gregoiredavid.fr/repo/departements.geojson), and the result is * 5 times !!

```js
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { serialize } from '../node_modules/flatgeobuf/lib/mjs/geojson.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const buffer = fs.readFileSync(path.join(__dirname, '../data/geo/states.json'))
const fileContent = JSON.parse(buffer.toString())

const flatgeobuf = serialize(fileContent)
fs.appendFileSync(path.join(__dirname, '../data/geo/states.fgb'), Buffer.from(flatgeobuf));
```

Thanks a lot !

**Comment by bjornharrtell** [comment]
Seems unexpected. Will look into it but might take some time before I have time for it.

**Comment by bjornharrtell** [comment]
Tried this now and I get 50% size reduction so I'm not sure what you are seeing. @bacloud22, are you sure you haven't run the code multiple times so that the resulting file is actually multiple appended results because you are using `appendFileSync`?

* departements.geojson - 1 079 714 bytes 
* departements.fgb - 514 904 bytes (created by ogr2ogr including spatial index)
* departements.fgb - 510 432 bytes (created by js/node code, no spatial index)

**Comment by bacloud22** [comment]
Ok cool thanks for the follow. Then append was surely stacking contents into it. I will try that later.
