### ISSUE TITLE
rust: document that `HttpFgbReader` won't work with `https` urls by default

### ISSUE THREAD

**Issue by msalib** [flatgeobuf/flatgeobuf#231]
I stumbled on this -- if you make a simple app using `flatgeobuf` that doesn't depend directly on `reqwest@0.11.0`, it will fail to handle `https` urls with this error message:

```
Error: http error `error sending request for url (https://blah/blah/blah.fgb): error trying to connect: invalid URL, scheme is not http`
```

That error originates in `hyper`. I think the issue is that `http-range-client` has an optional dependency on `reqwest` and so without that, you'll get a client that has no support for HTTPS. That's...really odd. I'd suggest either:
* document clearly that `HttpFgbReader` will not read HTTPS urls unless you add an explicit dependency on the same version of request that `flatgeobuf`'s `http-range-client` depends on, or
* add a tls or http feature to flatgeobuf and document that in the README.

**Comment by michaelkirk** [comment]
I agree. Rather than add more documentation, I think it's preferable to just do what people expect to be done anyway. For the same reason reqwest enables https by default, so should http-range-client. People fully expect an http client to be able to speak tls be default without needing to read documentation and pass special options.

I've opened a PR that does this here https://github.com/pka/http-range-client/pull/4
