### ISSUE TITLE
Feature request: Support for binary serialization of object/array values

### ISSUE THREAD

**Issue by kochizufan** [flatgeobuf/flatgeobuf#250]
Hi

Sorry if this topic has been discussed a lot in the past.

I found Object or array type values are serialized not as binary but as JSON text.

![image](https://user-images.githubusercontent.com/2221431/209505205-0e02e178-f6ec-43b7-b598-7208d0e643b7.png)
Example: Sorry in Japanese

I think this greatly hinders the improvement of the compression ratio.
Can I expect the function to binary serialize attribute values ​​of Object and Array types in future?

**Comment by bjornharrtell** [comment]
It could perhaps make sense to use binary encodings for more complex attribute data. It would need some kind of standardized metadata description so that a parser can use it to decode.

As of yet I've not been/had interest enough so I would not expect something in near future unless you are willing to contribute.

**Comment by kochizufan** [comment]
Same with #251, I understood this issue does not hold much priority.

**Comment by pka** [comment]
https://github.com/sozip/sozip-spec could be a solution on top of FlatGeobuf.
