### ISSUE TITLE
Feature request: Support for compressing large text data

### ISSUE THREAD

**Issue by kochizufan** [flatgeobuf/flatgeobuf#251]
Very large text data are stored as they are, without compression:

![image](https://user-images.githubusercontent.com/2221431/209506535-57a92d01-f51d-431e-9a82-8464fdabdef0.png)
Example: sorry in Japanese

Is it possible to store compressed (by zip or so?) data if text size were larger than threshold?
Is this silly idea?

**Comment by bjornharrtell** [comment]
I would rather suggest compressing the whole file to keep compression and format separate.

That said, you could use the binary columntype (https://github.com/flatgeobuf/flatgeobuf/blob/master/src/fbs/header.fbs#L41) and compress in any way you like then perhaps some metadata (https://github.com/flatgeobuf/flatgeobuf/blob/master/src/fbs/header.fbs#L41) to let users know it's compressed and how.

I've considered doing some kind of standardized metadata structure so that it can be interoperable but as of yet not enough interest.

**Comment by kochizufan** [comment]
> I would rather suggest compressing the whole file to keep compression and format separate.

Make sense, you're right.

I understood strength of FGB is colud-friendly (Byte Range request-friendly), minimizing data size is not main focus.
To achieve minimized data size, maybe using Accept-Encoding:gzip is the best. I agree. Thanks!
