### ISSUE TITLE
Index at the end when writing as a stream ?

### ISSUE THREAD

**Issue by mhugo** [flatgeobuf/flatgeobuf#257]
Hi.
I am investigating the use of flatgeobuf for on-the-fly generation of datasets. And I am wondering if we can find a way to still generate a spatial index in that case, because well ... a spatial index will greatly help opening big fgb files in applications like QGIS.

I was thinking about storing the index **at the end** of the stream, after all features, assuming one find a way to specify that layout in the header (either for the next format version or in a backward compatible way), and probably also store the number of features at the end so that the size of the index can be computed.

It seems ok for readers that work on files, but HTTP Range requests could not be used in that case: AFAIK there is no standard way to make a "seek from the end of the file" through HTTP range requests as it is possible on a file system. There might be ways to abuse the standard a bit to specify a "seek from the end" (asking for a excessively high offset, [using non standard units](https://stackoverflow.com/a/5063816), etc.), but this seems a bit hacky and assumes we can tweak the web server's behaviour to our needs (which defeats the purpose of storing those files on generic hosting providers)

But still, what do you think ? Would this kind of "deferred" index be of interest for other people ?

**Comment by bjornharrtell** [comment]
I'm open to discuss it but I'm not sure it can be done in a backwards compatible way which could be a deal breaker for me, since I have no current plans of a new major revision.

But I'm not sure I understand your use case. It is that you want to avoid the sorting step and write features in a random order then spatially index them after the fact? I'm wary of this since it means you will get a less optimal spatial index... which is perhaps defendable since I agree that the ability to stream write and still provide a spatial index even if it's not optimal. But my second concern is if the current index implementation can handle a unbalanced/nonfilled tree as is or if it would need more complex R-tree implementation to work at all. I do not like complexity.

**Comment by mhugo** [comment]
> It is that you want to avoid the sorting step and write features in a random order then spatially index them after the fact?

Ah. Your question makes me realize I don't understand enough how the spatial index works. If this requires a sub optimal index and a complex implementation, then I agree this is not something we want. Thanks for your answer

**Comment by bjornharrtell** [comment]
Generating spatial index is a relatively complex and computatively expensive operation. You preferably only want to do it once. If you have data that is often modified you really need a spatial index that can be modified too, which is a complex beast (IMHO) and is is what fx. PostgreSQL/PostGIS provides. FlatGeobuf can definitely be used as serialization format to transfer data in and out of PostGIS over some protocol but the spatial filtering is then best if left to occur in PostGIS (i.e filter first, serialize to FlatGeobuf after).

**Comment by bjornharrtell** [comment]
Closing for now.
