### ISSUE TITLE
How to do a range request for a Flatgeobuf stored as Azure Blob using Python

### ISSUE THREAD

**Issue by robertnagy1** [flatgeobuf/flatgeobuf#268]
Hi! 

Does anybody know by chance how to do a range request on a Flatgeobuf which is residing in Azure using python? Do you know about any standard library or if done with python requests, how a request should look like in python for a Flatgeobuf?

cheers,
Rob

**Comment by michaelkirk** [comment]
I'm assuming you want to select a subset of features within a bounding box like in this example: https://flatgeobuf.org/examples/leaflet/filtered.html

Is that right?

I'm not aware of any existing pure python client for flatgeobuf.  If you wanted to write one, here are the stand alone readers we have in other languages that might serve as good examples:

rust: https://github.com/flatgeobuf/flatgeobuf/blob/master/src/rust/src/http_reader.rs
typescript: https://github.com/flatgeobuf/flatgeobuf/blob/master/src/ts/http-reader.ts

Another avenue using existing code might be via python-ogr/gdal which supports flatgeobuf. Hoever, I don't know if that integration supports http/range, I have never tried.

**Comment by robertnagy1** [comment]
That is exactly what i want to do, i just conceptually have to figure out how it does it conceptually. How a one can search ranges, and how does a bounding box become a range. I'll skim through the code, even though i am not an expert in javascript or rust, so i have to make due with what i have. 

Thank you for your answer and your effort for the community, flatgeobufs seem perfect for serverless applications and that is why am trying to learn how to use them. If you don't mind me asking: Have you benchmarked it for concurrent users? how does it compare to a standard wms server?

**Comment by michaelkirk** [comment]
I've never benchmarked against WMS, but I can confidently say it will be slower, since the FGB client implementation has to make a series of network round trips as it traverses a remote index, whereas the WMS can do all that traversal locally. But depending on your dataset and use case it might be "fast enough" to be a good trade off if it means you can avoid an application server.

In my own experiences, the vast majority of time is spent waiting for network round trips. If you have a relatively large data set, of which you want a relatively small slice, you'll want to make sure you're doing what you can to optimize index traversal and merge feature data requests like we did here:

https://github.com/flatgeobuf/flatgeobuf/pull/117

And you'll want to host the dataset with as little latency as feasible - e.g. a globally distributed CDN.

You can get a rough idea for the shape of things by opening your browser developer console and looking at the US census tracts example at https://flatgeobuf.org/examples/leaflet/large.html which uses a typescript implementation optimized to trade off some "wasted" bytes in order to reduce the number requests.

We fetch 611kb from a 12GB file to get 113kb of feature data, so about 80% of the bandwidth is overhead from the index and fetching "wasted bytes" between merged nearby feature requests. This is done across 12 requests — some of which can be concurrent, but mostly they need to be done serially.

With a WMS server presumably this could be a single request with about a 113kb payload.

**Comment by michaelkirk** [comment]
>  Have you benchmarked it for concurrent users? how does it compare to a standard wms server?

Ack, I missed this part your question. As far as *concurrent* users, that's a spot where FGB really shines. Since all the traversal is done on the client side, there is no server side work to do other than to serve HTTP range requests, so it should scale very well in that regard.

**Comment by robertnagy1** [comment]
Pure gold! thank you @michaelkirk!
