### ISSUE TITLE
(Go) Usage of temp file in writer.Write

### ISSUE THREAD

**Issue by shihanng** [flatgeobuf/flatgeobuf#321]
The Go implementation uses a temp file to store the generated features temporarily:
https://github.com/flatgeobuf/flatgeobuf/blob/f25bfdeccace2abc7b65b7fb104a50563a2c1a76/src/go/writer/writer.go#L93-L94

I wonder why a temp file is used instead of an in-memory buffer and if the project is open to not using a temp file.

My motivation is that I want to compile a code that uses FlatGeobuf's Go package into WebAssembly (WASI). However, since using temp files means access to the host file system, it is not easy (I can't find a way yet) to do so.

**Comment by michaelkirk** [comment]
Do you need to write a FGB file from wasm or just read one?On Oct 7, 2023, at 16:36, Shi Han ***@***.***> wrote:﻿
The Go implementation uses a temp file to store the generated features temporarily:
https://github.com/flatgeobuf/flatgeobuf/blob/f25bfdeccace2abc7b65b7fb104a50563a2c1a76/src/go/writer/writer.go#L93-L94
I wonder why a temp file is used instead of an in-memory buffer and if the project is open to not using a temp file.
My motivation is that I want to compile a code that uses FlatGeobuf's Go package into WebAssembly (WASI). However, since using temp files means access to the host file system, it is not easy (I can't find a way yet) to do so.

**Comment by shihanng** [comment]
> Do you need to write a FGB file from wasm or just read one?

I need to create FGB content using WASM. I don't need to write it to a file; instead, the WASM will produce the FGB data in Go's byte slices and pass that to the caller.

**Comment by bjornharrtell** [comment]
@shihanng do you need the spatial index?

**Comment by shihanng** [comment]
> @shihanng do you need the spatial index?

@bjornharrtell Ahh... I see that if I don't need the spatial index, it will not use the temp file. I think I can get away without the spatial index for now. 

However, what if that is required in the future? Could we open the possibility of using memory instead of a temp file? Or supporting both? I am happy to contribute if that is a possibility.

**Comment by bjornharrtell** [comment]
@shihanng might make sense to introduce it as an option.

**Comment by bruno-ga** [comment]
Sorry I did not see this earlier. I will enable notifications for updates.

I made a couple comments in the PR:

1 - We should have a warning somewhere that this can potentially use arbitrarily large amounts of memory.
2 - The change is breaking the existing API. It is easy to sort it up so I suggested how to do it.

Other than that, I see no reason not to do this although this seems to be a very contrived usage scenario.
