### ISSUE TITLE
[feature request] allow empty layer name

### ISSUE THREAD

**Issue by tobwen** [flatgeobuf/flatgeobuf#400]
### description
I've often receive FlatGeobuf datasets that contain layer names that don't match the file names. One of the little advantages of Shapefiles was that they didn't have layer names. Software, like QGIS, just showed the layer name based on the filename.

People who are now migrating to FlatGeobuf sometimes save the file in QGIS as "<some-random-name>.fgb" and then rename it to the final file name before mailing or uploading it to the fileserver. In the worst case, this could even lead to the disclosure of internal company information if users are unaware that the file name is stored as the layer name.

Since FlatGeobuf only has one layer and also supports metadata, it should be possible to set an empty layer name or not set a layer name by default at all. Applications like QGIS should ignore empty layer names and use the file name instead - similar to how Shapefiles work.

**Comment by bjornharrtell** [comment]
I can't make name not required since that would be a breaking change.

It is allowed to set it to an empty string. Changing the default of the implementation in QGIS and elsewhere would however at best be confusing, at least in between versions.. so I'm hesistant to push for such a change. It would likely have to be a long term two step change, first ensuring that an empty name is well handled then later change the default. Since this would likely have to be a change in the FlatGeobuf driver of GDAL I wonder, @rouault do you have any opinion on this matter?

I admit the current behaviour can cause confusion too and is a bit unfortunate, and I possibly regret making name required and populated by reference implementations. But what would life be without regrets?

**Comment by rouault** [comment]
It would totally make sense for the read part of the OGR FlatGeoBuf driver to use layer_name = CPLGetBasename(filename) when the layer name from the FlatGeoBuf metadata is empty
On the writing side, it is not obvious we would want to systematically empty the layer name. Users might have good reason to honour the one passed through CreateLayer().

**Comment by rouault** [comment]
> Wouldn't it be possible to just send `-nln ""` to write an empty/no name or maybe `-lco NAME=EMPTY`?

current implementation of ogr2ogr considers as if the argument is not specified when using `-nln ""`. It is a big "illegal" to specify an empty layer name because that would mean you couldn't SQL request it if it was propagated to the reading side. yes, perhaps  "-lco NAME=" (an empty value would work contrary to ``-nln ""``) could be used

**Comment by tobwen** [comment]
> It is a big "illegal" to specify an empty layer name because that would mean you couldn't SQL request it if it was propagated to the reading side.

But isn't this the same case with a GeoJSON where the `name` attribute isn't set? The SQL query is still possible against the filename (without the extension). `test.geojson` just becomes the layer `test`.

**Comment by rouault** [comment]
> but isn't this the same case with a GeoJSON where the `name` attribute isn't set?

well on the writing side, drivers are more or less required to honour the named pass to CreateLayer() as much as possible. That is CreateLayer(some_string)->GetName() should normally return some_string, hence it is weird to accept an empty string here. Having some creation option to mean the layer name in the metadata should be empty is fine though.

**Comment by bjornharrtell** [comment]
I'm not sure where to go from here. I don't see what I can do in flatgeobuf by itself at this point. If an option is introduced as suggested to the GDAL driver it will be a bit obscure and difficult to explain (IMHO) and I suspect noone will bother to use it as is. But so, if the intended use of it is then in what QGIS does by default that will have to be proposed and planned for QGIS itself. In either case, it will require some efforts and persuasion elsewhere, and I'm far from convinced myself so I will not be pushing for it (at this time).

**Comment by tobwen** [comment]
Okay, no problem. Thanks for looking at it.
