### ISSUE TITLE
tippecanoe support

### ISSUE THREAD

**Issue by gertcuykens** [flatgeobuf/flatgeobuf#7]
Help @ericfischer out by giving him some more specific details maybe about flatgeobuf please, thx :)

see: https://github.com/mapbox/tippecanoe/issues/777

**Comment by bjornharrtell** [comment]
I will be happy to! :) First step seems to be to provide language support for Go which I'm prepared to help with. Initial tiny effort done with https://github.com/bjornharrtell/flatgeobuf/commit/d4a7ef08ac50e2b8f1230d36a7e4d9b80c493956. As with the other language support it would be beneficial to use dependencies that can serialize to and from WKT and/or GeoJSON into a memory model of simple features to be able to create full roundtrip tests, if you have any tips on any such dependencies in the Go community please let me know.

**Comment by bdon** [comment]
I'm completed a very basic implementation of this in my fork at https://github.com/protomaps/tippecanoe (version 2.1.0). 

It's only passed my test suite of all GDAL-created Natural Earth FGBs, and will likely break on others right now. I can manage issue tracking/feature requests in https://github.com/protomaps/tippecanoe/issues instead of this repository.

**Comment by bjornharrtell** [comment]
Nowdays we do have go reference implementation so I don't think I can do more here, closing.
